let listThreadData = {
  kind: "youtube#commentThreadListResponse",
  etag: "XJZxfXpCz-16I7lt4l3ibnCKfGA",
  nextPageToken: "QURTSl9pMnR2cTQzVUR4OXNPb05tMDdyY05MR01uVEhGT0ZrcVVCSmlVQWdHY05kZHJycVlqRHBYRUtHSW9kWFRfWkNCT2lYc2hPT1FRbw==",
  pageInfo: {
    totalResults: 20,
    resultsPerPage: 20,
  },
  items: [
    {
      kind: "youtube#commentThread",
      etag: "oWAuXRMLE1SD95g9jIA2R499ork",
      id: "UgxXLeFJX3467FOuTKF4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "kHbdDsfflFPzPRVArGLhDpimreg",
          id: "UgxXLeFJX3467FOuTKF4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay:
              "Today I played my vr head set and someone had a biddle and other people can hold it and when you let go of it it will fly and when I Looked at secret tunl and it was opened and the biddle was suppose to be in a water fall and I Looked every where I just could not find it in all of them",
            textOriginal:
              "Today I played my vr head set and someone had a biddle and other people can hold it and when you let go of it it will fly and when I Looked at secret tunl and it was opened and the biddle was suppose to be in a water fall and I Looked every where I just could not find it in all of them",
            authorDisplayName: "Carla Bowen",
            authorProfileImageUrl: "https://yt3.ggpht.com/ytc/AGIKgqMAbBdpSLLUd9lmAdfVL069yimqwODVETVheQ=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCaJJT-Mc9qdZGIE9rnbh9Sg",
            authorChannelId: {
              value: "UCaJJT-Mc9qdZGIE9rnbh9Sg",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T19:08:58Z",
            updatedAt: "2023-05-27T19:08:58Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "T03Bc8CuZnqqKFHtJ5WOlv0rJ4I",
      id: "UgzAWrTqUBArHdEkqnh4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "OUzCz5H_Ro-2y5zw7Sn4AkndV5A",
          id: "UgzAWrTqUBArHdEkqnh4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay:
              "So here’s my new mini game for the new map. Here me out, so in the new map there’s water. The taggers are sharks, sharks to be only out of the water for 10 seconds. If you’re out more than 10 seconds, you have to have another shark come and get you. Non lava monkeys are just normal, but when tagged they have to get in the water in ten seconds. Hopefully this can become a more common mini game.",
            textOriginal:
              "So here’s my new mini game for the new map. Here me out, so in the new map there’s water. The taggers are sharks, sharks to be only out of the water for 10 seconds. If you’re out more than 10 seconds, you have to have another shark come and get you. Non lava monkeys are just normal, but when tagged they have to get in the water in ten seconds. Hopefully this can become a more common mini game.",
            authorDisplayName: "𝗦𝗰𝗼𝗿𝗽𝗶𝗼𝘀 𝗥𝗲𝘅",
            authorProfileImageUrl: "https://yt3.ggpht.com/_oQ8kJpd_o02yv_L8TFmq27qu7VXhFsGfPHP_xuW1ec-eLNGM68mNX6YLry_69XgCWjVIFPdFT8=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCxx_05NQgnN4jK7vffxhQsA",
            authorChannelId: {
              value: "UCxx_05NQgnN4jK7vffxhQsA",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T16:54:52Z",
            updatedAt: "2023-05-27T16:54:52Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "1NE3OOYFHK0miODBMZoSPDF5-vU",
      id: "UgyV3NYb1J92KBqccxp4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "DZ5py7JRFtcZ9h0K-PMN-jgiPGA",
          id: "UgyV3NYb1J92KBqccxp4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "Boys",
            textOriginal: "Boys",
            authorDisplayName: "Warmacime010",
            authorProfileImageUrl: "https://yt3.ggpht.com/YNrrK-nR5lndy9Tt4WRerjdGNImpxMR2ZCsEfCKindAP-ojq8GHBTutWmUf9Zm6It_8sHdbtaQ=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UC5Xf1WUVz8DsfmEIMp_ok7A",
            authorChannelId: {
              value: "UC5Xf1WUVz8DsfmEIMp_ok7A",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T15:04:52Z",
            updatedAt: "2023-05-27T15:04:52Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "uMxnEYWbs6YeOhMJL7CmqHY5pO0",
      id: "UgxwhCoplUyPwO4BRKh4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "n2EZ7Wrew7Kx6X9Wr7BLBs7J_vs",
          id: "UgxwhCoplUyPwO4BRKh4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "Rest in peace mines 😢",
            textOriginal: "Rest in peace mines 😢",
            authorDisplayName: "Slixxgt",
            authorProfileImageUrl: "https://yt3.ggpht.com/EfeJC08ewQ2IpvgxU1ROBP3oAdb3i_1miAA3xM7BlcaVwnYNk6nwYpeNmIiMk5G0s3GpFXIE=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCWkZlRNwGSx_5z_uoGh194Q",
            authorChannelId: {
              value: "UCWkZlRNwGSx_5z_uoGh194Q",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T14:30:27Z",
            updatedAt: "2023-05-27T14:30:51Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "T7GyqvgTs968liCuMJxnr9qWQ3s",
      id: "Ugw5u2S1UVt1SBBMkjF4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "d9i1Um6vqvX7QRhmrDyGQSFj4dY",
          id: "Ugw5u2S1UVt1SBBMkjF4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "L update",
            textOriginal: "L update",
            authorDisplayName: "PLP XJ",
            authorProfileImageUrl: "https://yt3.ggpht.com/iIGVWOqSwlez_xRstwEokIHWR2u07DfBg_Sq9wQBgyWgD0L5IwsuyQXftCikKnIYNpoU1yP8=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UC4wH4J2F9K_4fx-kg8BgYHA",
            authorChannelId: {
              value: "UC4wH4J2F9K_4fx-kg8BgYHA",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T13:46:14Z",
            updatedAt: "2023-05-27T13:46:14Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "TsnWQz3JzOQq1TfzwbPGhMgTGG0",
      id: "UgxHmMgfDg6QEW4puDx4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "Lt3u9ZXnPnzN2NLRhsB3Ef-GBu8",
          id: "UgxHmMgfDg6QEW4puDx4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "No I&#39;m happy that caves are gone and I hope it is forever",
            textOriginal: "No I'm happy that caves are gone and I hope it is forever",
            authorDisplayName: "xdragon 7788",
            authorProfileImageUrl: "https://yt3.ggpht.com/urxPvzLkiFypP8HQh6lhQ4ye1VMxHdCMtIwZD0VBh0R9_C4CFM8KDzgqgTd6z86ANK57evvZbA=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCmbStVPO9SyRycMNSoigD9Q",
            authorChannelId: {
              value: "UCmbStVPO9SyRycMNSoigD9Q",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T10:21:34Z",
            updatedAt: "2023-05-27T10:21:34Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "b1FPHG4xgg0oJw7Vi4j6CIWhijc",
      id: "Ugy9ZgRZU6wGVvTdx0p4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "Ul3aEXdd9PvE8bOJGg4GcVVC74s",
          id: "Ugy9ZgRZU6wGVvTdx0p4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "you can hear simeone singing in the new beach music",
            textOriginal: "you can hear simeone singing in the new beach music",
            authorDisplayName: "Robin Dumas",
            authorProfileImageUrl: "https://yt3.ggpht.com/ytc/AGIKgqPx-S4l1k_st73kPaheByWN8gD4E_f0pg83XmNakYup7KprRz8hunAgYf7cMHOH=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCnf5KA8tu80Ak9nK2lW7ebg",
            authorChannelId: {
              value: "UCnf5KA8tu80Ak9nK2lW7ebg",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T09:40:06Z",
            updatedAt: "2023-05-27T09:40:06Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "iERxxYSoPqO43WhNmC1iSiIiB3A",
      id: "Ugyk8R-Eah0m5cLhjDl4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "x_cgqtlNKBgVSHc-xq01wddzQKQ",
          id: "Ugyk8R-Eah0m5cLhjDl4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "WHY ARE ALL OF THESE UPDATE VIDS 2 MINS LONG ON THIS UPDATE WHAT THE HE-",
            textOriginal: "WHY ARE ALL OF THESE UPDATE VIDS 2 MINS LONG ON THIS UPDATE WHAT THE HE-",
            authorDisplayName: "*• N _Murder drones •*",
            authorProfileImageUrl: "https://yt3.ggpht.com/M2xSBG7t0d35OpLE3XZjJLPxOpl8BHM7P5HGKGd4F0vFqMbWhgv8SuoThTcNVmJDou3q3WsgiQ=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UC_R1K0WBG-k-kdlaWq9Nq-Q",
            authorChannelId: {
              value: "UC_R1K0WBG-k-kdlaWq9Nq-Q",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T08:31:43Z",
            updatedAt: "2023-05-27T08:31:43Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "FzHuFvebnOCv1xX8OU8UB-ftTWw",
      id: "UgwwxvcDTWdKFMD263Z4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "4PPzcBtyq8ZmbktRk5heTT4Jg7I",
          id: "UgwwxvcDTWdKFMD263Z4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "Daddy said it’s my turn to get a pin",
            textOriginal: "Daddy said it’s my turn to get a pin",
            authorDisplayName: "Emma Glaister",
            authorProfileImageUrl: "https://yt3.ggpht.com/ytc/AGIKgqNbcpdZGAL-jwSBnOoWrE2v64Mwx_LFcPvOcA=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCfUUeaecpqEYJ19bTChCZlg",
            authorChannelId: {
              value: "UCfUUeaecpqEYJ19bTChCZlg",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T08:19:04Z",
            updatedAt: "2023-05-27T08:19:04Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "8kAzoCE368D7Uk2dz1CtvubIqbs",
      id: "Ugx3JxTSbym2o8qfFqp4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "IPc9gM1dYopaC3HzO2SG2xETt5I",
          id: "Ugx3JxTSbym2o8qfFqp4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "by bugs he means an actual beetle",
            textOriginal: "by bugs he means an actual beetle",
            authorDisplayName: "Gamekraze64",
            authorProfileImageUrl: "https://yt3.ggpht.com/ci3x0iNZH3YRW1l0R4SjWqqfJ6umUIGRTt4H5-p0FN4wP3nxbEgrFScwffnVjCJsla0ZRLP_Iw=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UC2An8JegNcy8CSdulIdgTrQ",
            authorChannelId: {
              value: "UC2An8JegNcy8CSdulIdgTrQ",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T07:53:39Z",
            updatedAt: "2023-05-27T07:53:39Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "PQHRJZGriQMjDOwM7XK6OJ-OyVE",
      id: "Ugze9W2WHBnd8chJ3gZ4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "LFt7WUSqWHqSruFs3xfa0wvAfmk",
          id: "Ugze9W2WHBnd8chJ3gZ4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "Hey rakzz you didn&#39;t look at the dlc",
            textOriginal: "Hey rakzz you didn't look at the dlc",
            authorDisplayName: "Dough fruit",
            authorProfileImageUrl: "https://yt3.ggpht.com/-hPKMGXiwlxgCytlnxKIlVEm_xOmwg4npznsqa3f6ks3-gYYijyimuWQdkpWrhmsZqPiUxYtpw=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCnyyHWSbFYPMuASPVnWY9tw",
            authorChannelId: {
              value: "UCnyyHWSbFYPMuASPVnWY9tw",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T06:01:50Z",
            updatedAt: "2023-05-27T06:01:50Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "9Py_swNIYHxmS5I4R_kxdha4lQo",
      id: "Ugx9mYF3jWz58cViiyl4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "7rCvxkP8iABi-gyZb8RHBQARq7A",
          id: "Ugx9mYF3jWz58cViiyl4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "Yeah",
            textOriginal: "Yeah",
            authorDisplayName: "Riley cox. channel",
            authorProfileImageUrl: "https://yt3.ggpht.com/_x4OVnCeOsEWPOz0L1511VqJHSfXhtF4_7lfzgdG73OeLQ73Ohux2faCxU5Bn35xqYxc3ltD9LI=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCllwr3YWaCInlW4NR9n30Eg",
            authorChannelId: {
              value: "UCllwr3YWaCInlW4NR9n30Eg",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T05:15:34Z",
            updatedAt: "2023-05-27T05:15:34Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "UHb8A_5F-GvcBE1aF_ad3SC2oP4",
      id: "UgwCYJfuXPXsiZvcdVl4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "CvDzqNxcAElR-Eo8GNLwsaFH4_0",
          id: "UgwCYJfuXPXsiZvcdVl4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "Fuck this rakzz was my favorite YouTuber but now he’s kinda shit for so many reasons",
            textOriginal: "Fuck this rakzz was my favorite YouTuber but now he’s kinda shit for so many reasons",
            authorDisplayName: "Mongoo",
            authorProfileImageUrl: "https://yt3.ggpht.com/PXsmHJ6_EhesMZDY61pQlBGOIIEYpfKcjihnsTPA5XLXJzKQzCeGUF4hEk9QTR_z3BelIPtIEQ=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCEBRghN7CK0OvpEXSQSVqsQ",
            authorChannelId: {
              value: "UCEBRghN7CK0OvpEXSQSVqsQ",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T04:03:28Z",
            updatedAt: "2023-05-27T04:03:28Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "xx-jnS7PjtHTuQ8372356b2-GKc",
      id: "UgxB0mhlFyM7K0-_GfB4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "e1Y7wJ1vjYy26EoGThVwbiEJ7Tg",
          id: "UgxB0mhlFyM7K0-_GfB4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "Bro I just got banned from rakzz  server because I’m 12 and it’s stupid most of his viewers are 12 and under so I’m unsubscribing this is so DUMB!",
            textOriginal: "Bro I just got banned from rakzz  server because I’m 12 and it’s stupid most of his viewers are 12 and under so I’m unsubscribing this is so DUMB!",
            authorDisplayName: "Mongoo",
            authorProfileImageUrl: "https://yt3.ggpht.com/PXsmHJ6_EhesMZDY61pQlBGOIIEYpfKcjihnsTPA5XLXJzKQzCeGUF4hEk9QTR_z3BelIPtIEQ=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCEBRghN7CK0OvpEXSQSVqsQ",
            authorChannelId: {
              value: "UCEBRghN7CK0OvpEXSQSVqsQ",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T04:01:44Z",
            updatedAt: "2023-05-27T04:01:44Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "RC3nkyvUaBNPSMnedIQhKDoNtUE",
      id: "UgyPzt8M_nqBLMgSoCZ4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "48Ufxv4oZmKjRf0-ccn6-fxIAmQ",
          id: "UgyPzt8M_nqBLMgSoCZ4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "Could do better lo man",
            textOriginal: "Could do better lo man",
            authorDisplayName: "Snoop.",
            authorProfileImageUrl: "https://yt3.ggpht.com/ytc/AGIKgqM25iv9GXOo3bB4dJhd8blGobE4fcimz5f7CJWZ=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCm2b9lLWYxyF8aJgDGZZSWQ",
            authorChannelId: {
              value: "UCm2b9lLWYxyF8aJgDGZZSWQ",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T02:47:13Z",
            updatedAt: "2023-05-27T02:47:13Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "Un9N7Uqfw8xaMKkgj6INp9BdZsM",
      id: "Ugz6ryK81-IUCDa4Yph4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "fz4Q4H62xlTGo0XPz3Kh8v1Xbf4",
          id: "Ugz6ryK81-IUCDa4Yph4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "Cavs will be back",
            textOriginal: "Cavs will be back",
            authorDisplayName: "shannon groga",
            authorProfileImageUrl: "https://yt3.ggpht.com/ytc/AGIKgqMUljsAjpL7-QsnL1EW_q0l1g3v6c88TcJenAFtojwfXBmm9fr5M6dMXTkV1ogx=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UC_QxJAOHJC7wJkDnezhbUxQ",
            authorChannelId: {
              value: "UC_QxJAOHJC7wJkDnezhbUxQ",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T02:27:13Z",
            updatedAt: "2023-05-27T02:27:13Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "Vy-_Uw6IbzFXgET6VBOzh03O2og",
      id: "UgxHTyiqJDkZHoQPTQ94AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "VNabKXmTfZ2O3Y9eqvQ8qSsSBis",
          id: "UgxHTyiqJDkZHoQPTQ94AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "Anybody noticed the bug",
            textOriginal: "Anybody noticed the bug",
            authorDisplayName: "shannon groga",
            authorProfileImageUrl: "https://yt3.ggpht.com/ytc/AGIKgqMUljsAjpL7-QsnL1EW_q0l1g3v6c88TcJenAFtojwfXBmm9fr5M6dMXTkV1ogx=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UC_QxJAOHJC7wJkDnezhbUxQ",
            authorChannelId: {
              value: "UC_QxJAOHJC7wJkDnezhbUxQ",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-27T02:24:36Z",
            updatedAt: "2023-05-27T02:24:36Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "eZncbV74cKcvHoYcQQpidYRDVM0",
      id: "UgxNzbC1xau0cOff7AJ4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "Kg9kKvMMZiHDsijs6PopvHXyhII",
          id: "UgxNzbC1xau0cOff7AJ4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay: "DONT FORGET THE DLC!",
            textOriginal: "DONT FORGET THE DLC!",
            authorDisplayName: "SCPCustom Founder",
            authorProfileImageUrl: "https://yt3.ggpht.com/dV5O-PhnX_0ftZm9kDu1cIDiG7LD-XYSNTdJgoq9d0_N2eGxiLv7-qLY_WkRv0V1gpEwE4PXJwk=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCT1atNp15L02cnHVfVqu_jg",
            authorChannelId: {
              value: "UCT1atNp15L02cnHVfVqu_jg",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 1,
            publishedAt: "2023-05-27T02:15:20Z",
            updatedAt: "2023-05-27T02:15:20Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "rkfVSQPzTad69CgUz6wlYm9dGXo",
      id: "Ugzd23nkN1V8_lHCajx4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "qnsHeir18XXL6IFoetqsmoCScx0",
          id: "Ugzd23nkN1V8_lHCajx4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay:
              "I am one of the OG gorilla tags players not beta but played when the giant stumped stairs where pole stairs and I found this secret tunnel by looking at a wall also there’s a stone wall in gorilla tag that looks like a face.",
            textOriginal:
              "I am one of the OG gorilla tags players not beta but played when the giant stumped stairs where pole stairs and I found this secret tunnel by looking at a wall also there’s a stone wall in gorilla tag that looks like a face.",
            authorDisplayName: "R̴o̸b̶o̵t̷ ̷n̸u̷m̷b̶e̷r̵ ̸7̷8̷7̷",
            authorProfileImageUrl: "https://yt3.ggpht.com/kjI4PZFtFH8X2ll7YUcI1Y0WZgVfTUgTvZ6_mQHsV1BqZJTIk6RQgaknY2UcwWjx3GcXdG8KIw=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCh7jytiuY3gIzhLXW38Y2ug",
            authorChannelId: {
              value: "UCh7jytiuY3gIzhLXW38Y2ug",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 1,
            publishedAt: "2023-05-27T02:13:22Z",
            updatedAt: "2023-05-27T02:13:22Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "LlaqmxXrlzpM9qid0SsI5GwgeAk",
      id: "Ugzmco926rCDnS7iqhl4AaABAg",
      snippet: {
        videoId: "-asEXTk9ibk",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "kjf0Vz6Iwu2lKDP42o2wH4bbgr4",
          id: "Ugzmco926rCDnS7iqhl4AaABAg",
          snippet: {
            videoId: "-asEXTk9ibk",
            textDisplay:
              "Rakzz can you help I play on index and everytime I open gorilla tag it keep saying gorilla tag not responding  and I updated everything and updated gorilla tag",
            textOriginal:
              "Rakzz can you help I play on index and everytime I open gorilla tag it keep saying gorilla tag not responding  and I updated everything and updated gorilla tag",
            authorDisplayName: "Giselle Marie",
            authorProfileImageUrl: "https://yt3.ggpht.com/83idjTScoGEbctV3Kan2g3OtWQsBmoVdfRkYQF4EVLS5Q3WASjSSFz5jMQGocBd-b3cgm0EkiSk=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCH1S40h5epUSdPbJmNSwgFQ",
            authorChannelId: {
              value: "UCH1S40h5epUSdPbJmNSwgFQ",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 1,
            publishedAt: "2023-05-27T01:57:40Z",
            updatedAt: "2023-05-27T01:57:51Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
  ],
};

listThreadData = {
  kind: "youtube#commentThreadListResponse",
  etag: "9ALHZlhYiM_2wZlfLbYBhUmxBlY",
  pageInfo: {
    totalResults: 5,
    resultsPerPage: 20,
  },
  items: [
    {
      kind: "youtube#commentThread",
      etag: "qrvUiU74o_2_WS5OEW5U0eUYJyY",
      id: "UgzRVN2qhan1N4M8yzl4AaABAg",
      snippet: {
        videoId: "zHfR96IZECQ",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "n3P1khrk65Bu9XAvZImmP2OI-ZE",
          id: "UgzRVN2qhan1N4M8yzl4AaABAg",
          snippet: {
            videoId: "zHfR96IZECQ",
            textDisplay: "Thanks a Lots for helping 🤩",
            textOriginal: "Thanks a Lots for helping 🤩",
            authorDisplayName: "Krishna Nayak",
            authorProfileImageUrl: "https://yt3.ggpht.com/ytc/AGIKgqPbuTr_miPkiANBbeCy2PAzB9oaptatMWPp3_fc2w=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCnGNmaO47ewyPqSe-G5OT7w",
            authorChannelId: {
              value: "UCnGNmaO47ewyPqSe-G5OT7w",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 0,
            publishedAt: "2023-05-29T09:19:19Z",
            updatedAt: "2023-05-29T09:19:19Z",
          },
        },
        canReply: true,
        totalReplyCount: 0,
        isPublic: true,
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "h0HgC7OCgL7jAG0y5X9kOtEIg-s",
      id: "Ugwbm9YKcG_NxMSwPIN4AaABAg",
      snippet: {
        videoId: "zHfR96IZECQ",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "LSGbkbDmBowsVPuFLBlwr2WBxrE",
          id: "Ugwbm9YKcG_NxMSwPIN4AaABAg",
          snippet: {
            videoId: "zHfR96IZECQ",
            textDisplay: "It helped a lot. Thanks",
            textOriginal: "It helped a lot. Thanks",
            authorDisplayName: "jaspreet singh",
            authorProfileImageUrl: "https://yt3.ggpht.com/ryGiAaywrVY6Y0B2xk7Py6wVu603lmab8nxXwHqEPiiJ4Tr_GE9U2BhDfQ8YYnEH7zuMnY5fiho=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UC8Sab6rpcrGlsE3o7jRRq8w",
            authorChannelId: {
              value: "UC8Sab6rpcrGlsE3o7jRRq8w",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 1,
            publishedAt: "2023-04-25T08:56:40Z",
            updatedAt: "2023-04-25T08:56:40Z",
          },
        },
        canReply: true,
        totalReplyCount: 1,
        isPublic: true,
      },
      replies: {
        comments: [
          {
            kind: "youtube#comment",
            etag: "Uphmgc-gIxFo3ibPT5iqHS87TCo",
            id: "Ugwbm9YKcG_NxMSwPIN4AaABAg.9ovWEppxu8G9ow67lcRNNV",
            snippet: {
              videoId: "zHfR96IZECQ",
              textDisplay: "Thanks for comment.",
              textOriginal: "Thanks for comment.",
              parentId: "Ugwbm9YKcG_NxMSwPIN4AaABAg",
              authorDisplayName: "Code Sagar",
              authorProfileImageUrl: "https://yt3.ggpht.com/83NrMV_XVrNjs9hpaoFOY7u2Ncgb5jqWIzz9Y6JNOCxvY40E6ar12nfXlCPBwiB1Q2_EmdldAw=s48-c-k-c0x00ffffff-no-rj",
              authorChannelUrl: "http://www.youtube.com/channel/UCQf65xqKfz95kWCzVwEGPbg",
              authorChannelId: {
                value: "UCQf65xqKfz95kWCzVwEGPbg",
              },
              canRate: true,
              viewerRating: "none",
              likeCount: 0,
              publishedAt: "2023-04-25T14:27:44Z",
              updatedAt: "2023-04-25T14:27:44Z",
            },
          },
        ],
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "Nbms5Wfqfotk1p-a4KaOcvC_Xrc",
      id: "UgwlEhu-PIsE3zc3AoR4AaABAg",
      snippet: {
        videoId: "zHfR96IZECQ",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "QqmIXEiGnZWc-R0Wg2Uf2odltsY",
          id: "UgwlEhu-PIsE3zc3AoR4AaABAg",
          snippet: {
            videoId: "zHfR96IZECQ",
            textDisplay: "Helpful 👏",
            textOriginal: "Helpful 👏",
            authorDisplayName: "Seema Sharma",
            authorProfileImageUrl: "https://yt3.ggpht.com/ytc/AGIKgqMlsQziVvSYlaLrS8Vwoc8WUJ76e2Bph-AiRJ00=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCCiqyDGFUOpnLUCqtdb4y7g",
            authorChannelId: {
              value: "UCCiqyDGFUOpnLUCqtdb4y7g",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 1,
            publishedAt: "2023-04-25T04:03:45Z",
            updatedAt: "2023-04-25T04:03:45Z",
          },
        },
        canReply: true,
        totalReplyCount: 1,
        isPublic: true,
      },
      replies: {
        comments: [
          {
            kind: "youtube#comment",
            etag: "XfEvriDIRyfoabWpuE-i6gtqQCI",
            id: "UgwlEhu-PIsE3zc3AoR4AaABAg.9ouziXVjI1e9ow68bop88f",
            snippet: {
              videoId: "zHfR96IZECQ",
              textDisplay: "Thanks for comment.",
              textOriginal: "Thanks for comment.",
              parentId: "UgwlEhu-PIsE3zc3AoR4AaABAg",
              authorDisplayName: "Code Sagar",
              authorProfileImageUrl: "https://yt3.ggpht.com/83NrMV_XVrNjs9hpaoFOY7u2Ncgb5jqWIzz9Y6JNOCxvY40E6ar12nfXlCPBwiB1Q2_EmdldAw=s48-c-k-c0x00ffffff-no-rj",
              authorChannelUrl: "http://www.youtube.com/channel/UCQf65xqKfz95kWCzVwEGPbg",
              authorChannelId: {
                value: "UCQf65xqKfz95kWCzVwEGPbg",
              },
              canRate: true,
              viewerRating: "none",
              likeCount: 0,
              publishedAt: "2023-04-25T14:27:51Z",
              updatedAt: "2023-04-25T14:27:51Z",
            },
          },
        ],
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "3ycRzYdQHbPUcQzAK6EWkESgGUA",
      id: "Ugzw0zrWpGJ6X8r_7AJ4AaABAg",
      snippet: {
        videoId: "zHfR96IZECQ",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "S7dxfxDEPxwzAMSe_bKHPbiAyHs",
          id: "Ugzw0zrWpGJ6X8r_7AJ4AaABAg",
          snippet: {
            videoId: "zHfR96IZECQ",
            textDisplay: "Helpful 👍 Thanks",
            textOriginal: "Helpful 👍 Thanks",
            authorDisplayName: "sandeep kaur",
            authorProfileImageUrl: "https://yt3.ggpht.com/ytc/AGIKgqNNxGYpbCcOC6Nddmubhmbvhn2RFBL_DaVgtzrfUA=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCvypajUDe1cGOT0m-oWxSkQ",
            authorChannelId: {
              value: "UCvypajUDe1cGOT0m-oWxSkQ",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 1,
            publishedAt: "2023-04-25T03:48:24Z",
            updatedAt: "2023-04-25T03:48:24Z",
          },
        },
        canReply: true,
        totalReplyCount: 1,
        isPublic: true,
      },
      replies: {
        comments: [
          {
            kind: "youtube#comment",
            etag: "1TNjUnFCXWaJwgdA3Gxh4pg7SmA",
            id: "Ugzw0zrWpGJ6X8r_7AJ4AaABAg.9ouxy5-xaGU9ow69Qsr5h9",
            snippet: {
              videoId: "zHfR96IZECQ",
              textDisplay: "Thanks for comment.",
              textOriginal: "Thanks for comment.",
              parentId: "Ugzw0zrWpGJ6X8r_7AJ4AaABAg",
              authorDisplayName: "Code Sagar",
              authorProfileImageUrl: "https://yt3.ggpht.com/83NrMV_XVrNjs9hpaoFOY7u2Ncgb5jqWIzz9Y6JNOCxvY40E6ar12nfXlCPBwiB1Q2_EmdldAw=s48-c-k-c0x00ffffff-no-rj",
              authorChannelUrl: "http://www.youtube.com/channel/UCQf65xqKfz95kWCzVwEGPbg",
              authorChannelId: {
                value: "UCQf65xqKfz95kWCzVwEGPbg",
              },
              canRate: true,
              viewerRating: "none",
              likeCount: 0,
              publishedAt: "2023-04-25T14:27:57Z",
              updatedAt: "2023-04-25T14:27:57Z",
            },
          },
        ],
      },
    },
    {
      kind: "youtube#commentThread",
      etag: "3YLzjdtqslVCCjjcjNuD5EQ33sA",
      id: "UgxpXnhGDvsv4bW_wc94AaABAg",
      snippet: {
        videoId: "zHfR96IZECQ",
        topLevelComment: {
          kind: "youtube#comment",
          etag: "vNlixZbjnycoozzCZEzJArrrBb8",
          id: "UgxpXnhGDvsv4bW_wc94AaABAg",
          snippet: {
            videoId: "zHfR96IZECQ",
            textDisplay: "best video. Step by step explaination.",
            textOriginal: "best video. Step by step explaination.",
            authorDisplayName: "jaspreet singh",
            authorProfileImageUrl: "https://yt3.ggpht.com/ytc/AGIKgqPhCpyqngAScn-PFiD40EnfCoQGLmR1nbLWfgQXVpo=s48-c-k-c0x00ffffff-no-rj",
            authorChannelUrl: "http://www.youtube.com/channel/UCDBqs79YQ5FmcOCFrFak9xQ",
            authorChannelId: {
              value: "UCDBqs79YQ5FmcOCFrFak9xQ",
            },
            canRate: true,
            viewerRating: "none",
            likeCount: 1,
            publishedAt: "2023-04-25T03:44:09Z",
            updatedAt: "2023-04-25T03:44:09Z",
          },
        },
        canReply: true,
        totalReplyCount: 1,
        isPublic: true,
      },
      replies: {
        comments: [
          {
            kind: "youtube#comment",
            etag: "o7h3XwecNd3sSETYjFPzPWRC-dw",
            id: "UgxpXnhGDvsv4bW_wc94AaABAg.9ouxTv7mUyO9ow6AGwuiTy",
            snippet: {
              videoId: "zHfR96IZECQ",
              textDisplay: "Thanks for comment.",
              textOriginal: "Thanks for comment.",
              parentId: "UgxpXnhGDvsv4bW_wc94AaABAg",
              authorDisplayName: "Code Sagar",
              authorProfileImageUrl: "https://yt3.ggpht.com/83NrMV_XVrNjs9hpaoFOY7u2Ncgb5jqWIzz9Y6JNOCxvY40E6ar12nfXlCPBwiB1Q2_EmdldAw=s48-c-k-c0x00ffffff-no-rj",
              authorChannelUrl: "http://www.youtube.com/channel/UCQf65xqKfz95kWCzVwEGPbg",
              authorChannelId: {
                value: "UCQf65xqKfz95kWCzVwEGPbg",
              },
              canRate: true,
              viewerRating: "none",
              likeCount: 0,
              publishedAt: "2023-04-25T14:28:04Z",
              updatedAt: "2023-04-25T14:28:04Z",
            },
          },
        ],
      },
    },
  ],
};
export default listThreadData;
